# Generated by Django 4.0.6 on 2022-07-19 14:21

from django.db import migrations, models
import myapp.specialfilefield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_file', myapp.specialfilefield.SpecialFileField(upload_to='myuploads/')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
